package edu.example.mycommunity.model;

public class Ad {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.title
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.url
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.image
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.gmt_start
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.gmt_end
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.status
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..ad.pos
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String pos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.id
     *
     * @return the value of mycommunity..ad.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.id
     *
     * @param id the value for mycommunity..ad.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.title
     *
     * @return the value of mycommunity..ad.title
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.title
     *
     * @param title the value for mycommunity..ad.title
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.url
     *
     * @return the value of mycommunity..ad.url
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.url
     *
     * @param url the value for mycommunity..ad.url
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.image
     *
     * @return the value of mycommunity..ad.image
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.image
     *
     * @param image the value for mycommunity..ad.image
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.gmt_start
     *
     * @return the value of mycommunity..ad.gmt_start
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtStart() {
        return gmtStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.gmt_start
     *
     * @param gmtStart the value for mycommunity..ad.gmt_start
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtStart(Long gmtStart) {
        this.gmtStart = gmtStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.gmt_end
     *
     * @return the value of mycommunity..ad.gmt_end
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtEnd() {
        return gmtEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.gmt_end
     *
     * @param gmtEnd the value for mycommunity..ad.gmt_end
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtEnd(Long gmtEnd) {
        this.gmtEnd = gmtEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.gmt_create
     *
     * @return the value of mycommunity..ad.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.gmt_create
     *
     * @param gmtCreate the value for mycommunity..ad.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.gmt_modified
     *
     * @return the value of mycommunity..ad.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.gmt_modified
     *
     * @param gmtModified the value for mycommunity..ad.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.status
     *
     * @return the value of mycommunity..ad.status
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.status
     *
     * @param status the value for mycommunity..ad.status
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..ad.pos
     *
     * @return the value of mycommunity..ad.pos
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..ad.pos
     *
     * @param pos the value for mycommunity..ad.pos
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setPos(String pos) {
        this.pos = pos == null ? null : pos.trim();
    }
}