package edu.example.mycommunity.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.parent_id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.type
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.commentator
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.like_count
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.content
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..comment.comment_count
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer commentCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.id
     *
     * @return the value of mycommunity..comment.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.id
     *
     * @param id the value for mycommunity..comment.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.parent_id
     *
     * @return the value of mycommunity..comment.parent_id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.parent_id
     *
     * @param parentId the value for mycommunity..comment.parent_id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.type
     *
     * @return the value of mycommunity..comment.type
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.type
     *
     * @param type the value for mycommunity..comment.type
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.commentator
     *
     * @return the value of mycommunity..comment.commentator
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.commentator
     *
     * @param commentator the value for mycommunity..comment.commentator
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.gmt_create
     *
     * @return the value of mycommunity..comment.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.gmt_create
     *
     * @param gmtCreate the value for mycommunity..comment.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.gmt_modified
     *
     * @return the value of mycommunity..comment.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.gmt_modified
     *
     * @param gmtModified the value for mycommunity..comment.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.like_count
     *
     * @return the value of mycommunity..comment.like_count
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.like_count
     *
     * @param likeCount the value for mycommunity..comment.like_count
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.content
     *
     * @return the value of mycommunity..comment.content
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.content
     *
     * @param content the value for mycommunity..comment.content
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..comment.comment_count
     *
     * @return the value of mycommunity..comment.comment_count
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..comment.comment_count
     *
     * @param commentCount the value for mycommunity..comment.comment_count
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
}