package edu.example.mycommunity.model;

public class Nav {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.title
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.url
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.priority
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycommunity..nav.status
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.id
     *
     * @return the value of mycommunity..nav.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.id
     *
     * @param id the value for mycommunity..nav.id
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.title
     *
     * @return the value of mycommunity..nav.title
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.title
     *
     * @param title the value for mycommunity..nav.title
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.url
     *
     * @return the value of mycommunity..nav.url
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.url
     *
     * @param url the value for mycommunity..nav.url
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.priority
     *
     * @return the value of mycommunity..nav.priority
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.priority
     *
     * @param priority the value for mycommunity..nav.priority
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.gmt_create
     *
     * @return the value of mycommunity..nav.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.gmt_create
     *
     * @param gmtCreate the value for mycommunity..nav.gmt_create
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.gmt_modified
     *
     * @return the value of mycommunity..nav.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.gmt_modified
     *
     * @param gmtModified the value for mycommunity..nav.gmt_modified
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycommunity..nav.status
     *
     * @return the value of mycommunity..nav.status
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycommunity..nav.status
     *
     * @param status the value for mycommunity..nav.status
     *
     * @mbg.generated Sun Apr 26 18:47:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}